import { useEffect, useMemo, useState } from "react";
import { formatDate, formatSol, sha256Hex } from "../lib/format";
import { buildInvoice, invoiceHash, type Invoice } from "../lib/invoice";
import type { Agreement, Order } from "../lib/types";

// The invoice document itself. Full addresses are shown so the printed PDF stands on its own.
export function InvoiceDocument({ invoice }: { invoice: Invoice }) {
   return (
      <div className="invoice">
         <div className="invoice-head">
            <h3>Invoice {invoice.number}</h3>
            <span className="muted small">Order #{invoice.orderId}</span>
         </div>
         <dl className="facts">
            <dt>From (3PL)</dt>
            <dd className="mono break">{invoice.provider}</dd>
            <dt>Bill to (client)</dt>
            <dd className="mono break">{invoice.client}</dd>
            <dt>Courier</dt>
            <dd className="mono break">{invoice.courier}</dd>
            <dt>Order registered</dt>
            <dd>{formatDate(invoice.createdAt)}</dd>
            <dt>Paid into escrow</dt>
            <dd>{invoice.paidAt !== null ? formatDate(invoice.paidAt) : "Not paid"}</dd>
         </dl>
         <table className="table invoice-lines">
            <thead>
               <tr>
                  <th>Service</th>
                  <th>Paid out to</th>
                  <th className="num">Amount</th>
               </tr>
            </thead>
            <tbody>
               {invoice.lines.map((l) => (
                  <tr key={l.description}>
                     <td>{l.description}</td>
                     <td className="mono break">{l.payTo}</td>
                     <td className="num">{formatSol(BigInt(l.lamports))}</td>
                  </tr>
               ))}
            </tbody>
            <tfoot>
               <tr>
                  <th colSpan={2}>Total (held in escrow until delivery)</th>
                  <th className="num">{formatSol(BigInt(invoice.totalLamports))}</th>
               </tr>
            </tfoot>
         </table>
         <p className="small muted">
            Order account <span className="mono break">{invoice.order}</span> · program{" "}
            <span className="mono break">{invoice.program}</span> · format {invoice.format}
         </p>
      </div>
   );
}

// Rebuilds the invoice from chain data and checks it against the fingerprint the 3PL stored.
export function InvoicePanel({ agreement, order }: { agreement: Agreement; order: Order }) {
   const invoice = useMemo(() => buildInvoice(agreement, order), [agreement, order]);
   const hash = useInvoiceHash(invoice);
   const [open, setOpen] = useState(false);
   if (!order.invoiceHash) return null;
   const matches = hash === null ? null : hash === order.invoiceHash;

   return (
      <div className="sub">
         <div className="row">
            <button onClick={() => setOpen(!open)}>{open ? "Hide invoice" : "View invoice"}</button>
            {open && matches && <button onClick={() => window.print()}>Download PDF</button>}
         </div>
         {matches === true && (
            <p className="ok-text small">✓ Matches the invoice fingerprint recorded on-chain.</p>
         )}
         {matches === false && <LegacyInvoiceCheck hash={order.invoiceHash} />}
         {open && matches && <InvoiceDocument invoice={invoice} />}
      </div>
   );
}

// Invoices sent before invoices were generated by the app were fingerprints of an uploaded
// file. Those can only be checked by someone who holds that file.
function LegacyInvoiceCheck({ hash }: { hash: string }) {
   const [result, setResult] = useState<"match" | "mismatch" | null>(null);
   return (
      <div className="small">
         <p className="muted">
            This invoice was uploaded as a file, not generated by the app. Fingerprint (SHA-256):{" "}
            <span className="mono break">{hash}</span>
         </p>
         <label>
            Verify the invoice file:{" "}
            <input
               type="file"
               onChange={async (e) => {
                  const file = e.target.files?.[0];
                  if (!file) return;
                  const h = await sha256Hex(await file.arrayBuffer());
                  setResult(h === hash ? "match" : "mismatch");
               }}
            />
         </label>
         {result === "match" && <p className="ok-text">✓ This file is the invoice recorded on-chain.</p>}
         {result === "mismatch" && <p className="error">✗ This file does not match the on-chain invoice.</p>}
      </div>
   );
}

function useInvoiceHash(invoice: Invoice): string | null {
   const [hash, setHash] = useState<string | null>(null);
   useEffect(() => {
      let live = true;
      invoiceHash(invoice).then((h) => live && setHash(h));
      return () => {
         live = false;
      };
   }, [invoice]);
   return hash;
}
